### ISSUE TITLE
Error in definition of (-) in symb.lhsren

### ISSUE THREAD

**Issue by abid-mujtaba** [hepek/Ramblings#1]
The definition of the function (-) inside the instance Num is incorrect.

Currently: (-) = flip Sum . Neg

Correct: (-) = flip $ Sum . Neg

since we want the inversion of the arguments to happen to the composed function and not just Sum. As it currently stands flip Sum . Neg is equivalent to (flip Sum) . Neg

**Comment by abid-mujtaba** [comment]
This still leaves the output inverted as in: x - y = (-y + x). I prefer (x +  -y) so I changed the definition to:

a - b = Sum a (Neg b)

**Comment by hepek** [comment]
Thank you. Too much point-free exibitionism on my side.

**Comment by hepek** [comment]
@abid-mujtaba exactly what I did. Thanks again.
